# Generated by Django 5.1.4 on 2025-01-11 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newBlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='write',
            name='slug',
            field=models.SlugField(default=models.TextField(max_length=255), unique=True),
        ),
    ]
