# Generated by Django 5.1.4 on 2025-01-11 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newBlog', '0002_write_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='write',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
