# Generated by Django 5.1.4 on 2025-01-12 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newBlog', '0003_alter_write_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='write',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
