# Generated by Django 5.1.4 on 2025-01-12 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newBlog', '0005_alter_write_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='write',
            name='slug',
        ),
    ]
